development:
  sessions:
    default:
      database: router_development
      hosts:
        - localhost:27017
      options:
  options:

production:
  sessions:
    default:
      database: router
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: router_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
